### ISSUE TITLE
Cleanly separate out the construction of entry points

### ISSUE THREAD

**Issue by FFY00** [pradyunsg/installer#8]
Some distributions, like Arch Linux, want us to have separate build and install steps. This means that .pyc files and entrypoint scripts would be built in a separate step. For this I propose having a command to do this. We could call it something like "build", "build cache", "generate cache", etc?

It would look like this
```
python -m installer --build something.whl
```

Then to install
```
python -m installer something.whl
```

Maybe we could also add an option to fail on missing pre-built files, so that we can enforce it inside the distribution workflows.

It would also be great if the command was accessible as an api, so that I could call it directly in [python-build](https://github.com/FFY00/python-build), making the final workflow for PEP517 projects something like:

```
(strictly build)
python -m build

(strictly install)
python -m install --destdir path/to/folder dist/something.whl
```

**Comment by brettcannon** [comment]
I will say I don't think `.pyc` file generation should be a part of this project; you can do that with `compileall` from the stdlib w/o issue. As for breaking out entrypoint generation, I view that as part of the installation process and not really a build step.

**Comment by pradyunsg** [comment]
It should be possible to write a small Python script to use the API provided by this project to do the generation of entry points for a wheel file, and that would be the approach for achieving the behavior you're looking for.

I don't think this project would even try to cater to any workflow other than "install a given wheel, using this `scheme`" via the CLI. I consider this out of scope for this project's CLI and it can be achieved by a user by using the library's API.

**Comment by gaborbernat** [comment]
> I will say I don't think `.pyc` file generation should be a part of this project; As for breaking out entrypoint generation, I view that as part of the installation process and not really a build step.

Duno the name of this project is ``installer``, I'd expect to fully take care of all jobs of given a wheel install it (so all sub-steps: extract, install, generate pyc etc). That being said, don't mind me. The more we talk about things the less convinced I'm that this project could work for virtualenv requirements (mostly because virtualenv is very special, and wants to optimize a lot of stuff - elements that might not make sense for a project that just wants to provide a wheel installer 🤷 ).

**Comment by FFY00** [comment]
> I will say I don't think `.pyc` file generation should be a part of this project; you can do that with `compileall` from the stdlib w/o issue.

Well, how will this project handle `.pyc` files then? Yes you can generate `.pyc` files but that is not the point. If was an isolated step it would be fine to ask the user to handle it himself, but it isn't.
My proposal here would result in the build step generating a `.installer-cache` folder with all the required extra files and then the install step just extracting the wheel contents and copying over the extra files. This would be equivalent as `setup.py build` and `setup.py install --skip-build`.

> As for breaking out entrypoint generation, I view that as part of the installation process and not really a build step.

I don't agree, you are generating an entrypoint script for a specific machine, how is this part of the installation? In the installation step you should be... installing, not generating anything. It does not make sense to me how generating a script is not something that should be done in a build step.

> It should be possible to write a small Python script to use the API provided by this project to do the generation of entry points for a wheel file, and that would be the approach for achieving the behavior you're looking for.

I am fine with this just being provided as an API, as long as it is provided. But then I don't really understand why you wouldn't expose it in the CLI since you would only have to write the CLI interface code, which should relatively low maintenance.

> I don't think this project would even try to cater to any workflow other than "install a given wheel, using this `scheme`" via the CLI. I consider this out of scope for this project's CLI and it can be achieved by a user by using the library's API.

Why? There is a need, as I pointed out. It is a pretty standard procedure to have separate build and install steps, although I do understand you might want to abstract that away from the users. But I don't think that is reason enough to decline it for the users that do need it and leave them to write their own specialized install tool using this project API. I am not saying to write a tool that works for everyone, what I am asking is to write a tool that works for the biggest players: majority of the users and distributions.

**Comment by brettcannon** [comment]
@FFY00 

> Well, how will this project handle .pyc files then?

It most likely won't.

I think you're misunderstanding the goal of this project. It's purpose is to create a low-level library that can handle wheel-specific installation details. It is **not** a goal to create a new pip or something with a rich CLI. Any CLI provided here is going to be proof-of-concept/dead-simple. IOW think of this project as providing a library for use _by_ pip, not to _replace_ pip.

**Comment by FFY00** [comment]
> It's purpose is to create a low-level library that can handle wheel-specific installation details

Can you specify? From that description the only routine that comes to mind is entrypoint script generation? Which other routines should this implement?

> Any CLI provided here is going to be proof-of-concept/dead-simple.

That is wrong IMO, you either provide a reasonably usable CLI or nothing at all. You can provide an example CLI but it should not be shipped, that will just generate confusion. When you make something available to users, they will use it.

> IOW think of this project as providing a library for use by pip, not to replace pip.

But why does it need to be just that? Why can't it expose the API as CLI, too? 

For my use-case I need a CLI which would be able to install a package, with some options. I can write it in a separate project but that feels silly, I don't see a reason why we shouldn't be able to provide a CLI. You can provide a library and a CLI, they are independent.

pip is not suitable for my needs for several reasons. I don't see why this project couldn't export a standalone CLI to install wheels instead of forcing me to write just that in a separate package. If you want to make this also available on pip, that is your call, but I believe there should be a simple standalone CLI to install wheels for users like distributions to use.

**Comment by brettcannon** [comment]
> Can you specify? From that description the only routine that comes to mind is entrypoint script generation? Which other routines should this implement?

See https://www.python.org/dev/peps/pep-0427/.

> That is wrong IMO, you either provide a reasonably usable CLI or nothing at all.

You're welcome to think that, but it's still out of scope for this project. We are building a library here, not a tool or app.

> But why does it need to be just that? Why can't it expose the API as CLI, too?

Because that's a lot of work and it isn't our focus here.

> You can provide a library and a CLI, they are independent.

**Exactly**, they are independent. Thus we do not want to do a CLI here as it's an separate and independent problem. Getting that right will be one of those things where everyone wants what they want and it can spiral out of control (e.g. you want to compile to `.pyc` files, I don't).

> I believe there should be a simple standalone CLI to install wheels for users like me to use.

Totally reasonable thing to want, but that can be done as a separate project.

**Comment by FFY00** [comment]
I am really sorry for my bluntness, I am becoming more frustrated with this by the second but please try to bear with me.

> @brettcannon changed the title ~~Allow pre-building the required files~~ Cleanly separate out the construction of entry points

That is not really what is being discussed here, I stand by the original title.

> > Can you specify? From that description the only routine that comes to mind is entrypoint script generation? Which other routines should this implement?
> 
> See [python.org/dev/peps/pep-0427](https://www.python.org/dev/peps/pep-0427/).

That is the wheel specification, it does not answer at all my question. So I ask again, which routines should be implemented here? If you think they are so obvious that pointing to the wheel specification is enough, you shouldn't have much problem listing them to me. So, if you could spend a minute clarifying this, I would greatly appreciate it.

> > That is wrong IMO, you either provide a reasonably usable CLI or nothing at all.
> 
> You're welcome to think that, but it's still out of scope for this project. We are building a library here, not a tool or app.

Then don't ship a CLI, that is my main point. If you only want a proof-of-concept CLI, **please** don't ship it.

> > But why does it need to be just that? Why can't it expose the API as CLI, too?
> 
> Because that's a lot of work and it isn't our focus here.
> 
> > You can provide a library and a CLI, they are independent.
> 
> **Exactly**, they are independent. Thus we do not want to do a CLI here as it's an separate and independent problem. Getting that right will be one of those things where everyone wants what they want and it can spiral out of control (e.g. you want to compile to `.pyc` files, I don't).

Respectfully, I don't think it is that hard, but I'll defer. I still think this would be the correct place for it but I do understand your point.
Leaving out the complexity issue, do you think this is something that should be provided here? Or do you still think it should be provided externally? Keep in mind that this would basically be just an interface to the exported API.
If so, giving your reluctance I can implement it externally and in the future we could think about merging it. What do you think?

> > I believe there should be a simple standalone CLI to install wheels for users like me to use.
> 
> Totally reasonable thing to want, but that can be done as a separate project.

**Comment by eli-schwartz** [comment]
From the description of this github repo:

> Someone said something about Python wheels, installation and maybe... a CLI.

I posit that a CLI is in scope. Given a CLI is in scope, it should be a reasonably robust implementation of a CLI (rather than a deliberately garbage proof of concept designed for uselessness) to just install a wheel, and to keep things simple, why not -- let's say also without quibbling, fuss, or micro-optimizing options.

It may be clear to @FFY00 that entry points should be generated in a separate phase, but it's not clear to me. It's *definitely* not clear to me that this is something the PyPA need concern itself with. @brettcannon on this I agree.

I would, however, say that I would consider generating pyc as part of `python -m installer --rootdir "$DESTDIR" something.whl` (right after installing the wheel) to be in scope. I'm curious under what conditions generating pyc might be seen as bad? But if there are conditions in which it is considered bad, perhaps it should be limited to only the `__main__` entry point.

There's at least one irritating edge case for running bare compileall, which is that you really want to trim off the leading --rootdir in the embedded paths and it's fairly awkward to do so properly. I would also not be averse to automatically handling `opt-1.pyc`.

I'm not going to devote my time to argue in favor of providing a special subcommand for pyc generation, but I would like to argue against refusing to do it at all.

(If anyone really, truly wants to separate out the build step from the install step, they can `python -m installer --rootdir ./temp something.whl` to "build", and then `cp -a` to "install". This should make literally everyone happy.)

**Comment by brettcannon** [comment]
> If you think they are so obvious that pointing to the wheel specification is enough, you shouldn't have much problem listing them to me. So, if you could spend a minute clarifying this, I would greatly appreciate it.

I sent you that link because I don't have the time to list it all out. I have already sunk way more time than I probably should trying to explain that your desire for a CLI that does everything you want is very likely out of scope.

> Then don't ship a CLI, that is my main point. If you only want a proof-of-concept CLI, please don't ship it.

OK, this has now degraded into feeling like people are _telling_ folks what to do instead of _asking_ simply because it isn't what they want.  I know there isn't any malice behind any of this nor the intent of what you're saying, but I am now stepping away from this issue for my own well-being.

> I'm curious under what conditions generating pyc might be seen as bad?

I am going to wager you didn't live through the 2 -> 3 transition. 😉 Beyond me thinking `.pyc` compilation is not inherent to installing from a wheel (which is the focus of this library), not everyone wants it (hence why there's an environment variable to suppress it), there's also the fact that if you have 2-only code and 3-only code in a wheel mixed so it's a universal wheel then bytecode compilation can fail and some people want to know when that happens and some don't. I dealt with issue [just earlier today](https://gitlab.com/python-devs/importlib_resources/-/issues/95).

**Comment by uranusjr** [comment]
I don’t think it is decided at all that we want to do a CLI. Maybe we do, but that should be a topic to be discussed after we actually have all the components needed for it.

I do agree that if we do implement a CLI, it can be a good idea for it to automatically compile pyc files, since it is not very convenient for the user to call compileall after the installation command is run (the command does not return where the package is installed). But `installer` would not have an API for that, and should instead just call `compileall` in the entry point—because the user can call `compileall` themselves if they are using the Python interface.

One additional thought about the CLI (again with the caveat that I don’t think it’s time for the discussion yet) is it should have minimal flags, i.e. if we want to compile pyc, it should always do that. I think it’s clear this project is library-first, so the CLI should only need to cover the most common case. Any more fine-tuned usage should go straight for the Python API.

**Comment by pradyunsg** [comment]
*sighs and takes a deep breath*

Here's what the goal for this project is: To provide a library that has all the utilities for installing a wheel file in a user environment, and all the functionality around it that is "relevant" *and* not already provided in an easy accessible location. It is **not** a goal to provide all the functionality that consumers could want.

In other words, this project is intended to provide the tools to work with wheels, for installing them -- consumers bring the wheels and process "quirks" that they want to use for manipulating/installing them. Ideally, these tools would make it simple (not easy!) to develop functionality/behaviors that the consumers (pip/virtualenv/distros/whatever) would want. It's very likely that some use cases would need more work to implement using this library than others, but that has to be done to keep this library from becoming a catch-all for the process quirks that the various consumers have.

This project is currently in a state where we're figuring out if it's even possible to come up with something that works for most (if not all) of the consumers' needs. That's the point of #1 -- collect all the use cases consumers have and see if we can come up with something that's workable for folks involved. I'll note that #1 is still open because that isn't done yet. We're looking for folks to tell us "what do you want to do" and not "how you want this project to do \<thing>". If you've stated the former, that's great! If you're gonna state the latter, it's not productive. :)

PS: I do know that it would've been better to keep the "collect use cases" and "design for use cases" steps in separate issues (and "far apart" from each other) instead of bundling them together in #1.  I took that shortcut there because I thought I would have the time to do the work and get away with it. However, I haven't had as much time to work on this project as I would've liked.

---

> I don’t think it is decided at all that we want to do a CLI. Maybe we do, but that should be a topic to be discussed after we actually have all the components needed for it.

+1

If it isn't obvious to everyone here already, there are a *lot* of potential consumers of the "unpack and do something with a wheel" related functionality, with varying/conflicting requirements. If it's not possible to cater to those requirements with a cohesive CLI, this project won't even try to do that. I did feel earlier that it'd still be useful to have a minimal CLI that does "install a wheel, with the given scheme" and for everything else say "write your own", but I'm starting to think that might not be a great idea.

---

My takeaways from this discussion are that:

- @FFY00 wanted to convey Arch Linux has a need for being to be able to perform "move files to the appropriate directories" in a separate step from everything else. This is definitely very useful to know. Thanks @FFY00!

- More communication about the intent of the project and "what is happening" would've been good, since folks are inferring things that aren't true / misinterpreting statements as being more than they are.

- I was wrong to think that folks understood that we weren't designing with everyone's inputs ("design by community" doesn't work) but rather collecting information from everyone about their use case, and *then* a subset (folks with the commit bit here) are gonna do the "designing" part using that information.

- There's a lot of people with strong opinions and things get heated very quickly<sup>1</sup> (in the time I was sleeping, this discussion got heated enough, that folks decided to stepping away is better than engaging further). I *really* don't want to end up having to make BDFL-esque choices on this project, but I'm gonna consider that as a reasonable option for this project, if things continue being the way that they are right now.

<sup>1</sup>I should've anticipated this. I've seen this pattern in this space, so many times now.

---

I'm going to go ahead and close this issue now, since I don't think there's anything else here that warrants further discussion; and if someone else thinks there is, I prefer that folks file a new issue/use a different communication channel to reach out to me.
