### ISSUE TITLE
Move project under PyPA?

### ISSUE THREAD

**Issue by layday** [pradyunsg/installer#88]
With the latest announcement on the packaging Discourse encouraging redistributors to use installer, should it perhaps be moved under the PyPA as the "blessed" tool for installing wheels sans pip?  There are no contenders in this space and installer is no doubt a high-quality package that the packaging community would benefit from.

**Comment by astrojuanlu** [comment]
May I ask which announcement? Just for curiosity :)

**Comment by layday** [comment]
https://discuss.python.org/t/debundling-the-next-pip-release-will-require-handling-pyproject-toml-based-build-backends/12329

**Comment by pradyunsg** [comment]
Started the vote. https://mail.python.org/archives/list/pypa-committers@python.org/thread/DB67USKXWCGSN4ZCQST4XIBRU7XPEUC3/

I'll close this eagerly since I don't think this needs to track the project moving into the PyPA, if the vote passes. That'll be an action item for whomever ends up doing the transfers and can be tracked on that thread instead. :)
